"""add_execution_candle_index

Revision ID: a2d639ecd5d5
Revises: 20260816_0002
Create Date: 2026-08-21 21:25:59.449896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d639ecd5d5'
down_revision: Union[str, Sequence[str], None] = '20260816_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executions', sa.Column('execution_candle_index', sa.Integer(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('executions', 'execution_candle_index')
    # ### end Alembic commands ###
